export const forumData = {
  accountId: "98767-888-78767",
  username: "tanaypratap",
  name: "Tanay Pratap",
  picUrl: "http://bit.ly/42Zm7tM",
  posts: [
    {
      postId: "36635-787-65778",
      username: "tanaypratap",
      name: "Tanay Pratap",
      picUrl: "http://bit.ly/42Zm7tM",
      post: "Join InvactHQ for MBA",
      postDescription:
        "Non programmers on my timeline. Attention! After placing 100+ programmers i in top Indian startups, I am thinking of coming up with a program for business roles as well. Interested in helping me build this course? Join me at Invact.",
      upvotes: 350,
      downvotes: 50,
      tags: ["mba", "business", "bootcamp"],
      createdAt: "2023-06-24T12:00:00Z",
      comments: [
        {
          commentId: "89898-856-87576",
          username: "ashwin4real",
          picUrl: "http://bit.ly/42Zm7tM",
          likes: 0,
          comment: "Interested",
          createdAt: "2023-06-24T12:01:00Z",
        },
      ],
      isBookmarked: false,
    },
    {
      postId: "36698-343-321232",
      username: "trishajain",
      name: "Trisha Jain",
      picUrl: "http://bit.ly/42Zm7tM",
      post: "Can I learn HTML, CSS, and JavaScript in 1 year?",
      postDescription:
        "I am looking to make my career in web development and want to learn these technologies. Can I learn these in 1 year and get a job?",
      upvotes: 150,
      downvotes: 0,
      tags: ["html", "javascript", "web development"],
      createdAt: "2023-06-24T12:54:00Z",
      comments: [],
      isBookmarked: false,
    },
    {
      postId: "23567-987-34567",
      username: "johnsmith",
      name: "John Smith",
      picUrl: "http://bit.ly/42Zm7tM",
      post: "Exciting internship opportunity at XYZ Company",
      postDescription:
        "XYZ Company is offering a summer internship program for students interested in gaining hands-on experience in the field of marketing. If you are passionate about marketing and eager to learn, don't miss this opportunity!",
      upvotes: 120,
      downvotes: 10,
      tags: ["internship", "marketing", "opportunity"],
      createdAt: "2023-06-24T14:30:00Z",
      comments: [
        {
          commentId: "34567-654-98765",
          username: "jennifergreen",
          picUrl: "http://bit.ly/42Zm7tM",
          likes: 2,
          comment: "I'm interested! Could you please provide more details?",
          createdAt: "2023-06-24T14:31:00Z",
        },
        {
          commentId: "23456-765-87654",
          username: "alexturner",
          picUrl: "http://bit.ly/42Zm7tM",
          likes: 5,
          comment: "This sounds like a great opportunity. I'll definitely apply!",
          createdAt: "2023-06-24T14:32:00Z",
        },
      ],
      isBookmarked: false,
    },
    {
      postId: "89765-432-12345",
      username: "sarahbrown",
      name: "Sarah Brown",
      picUrl: "http://bit.ly/42Zm7tM",
      post: "New Python tutorial series",
      postDescription:
        "I've started a new tutorial series on Python programming. If you're a beginner and want to learn Python, check it out on my YouTube channel!",
      upvotes: 250,
      downvotes: 20,
      tags: ["python", "tutorial", "programming"],
      createdAt: "2023-06-24T15:15:00Z",
      comments: [
        {
          commentId: "56789-987-65432",
          username: "mikerobinson",
          picUrl: "http://bit.ly/42Zm7tM",
          likes: 3,
          comment: "Your tutorials are always helpful. Looking forward to this series!",
          createdAt: "2023-06-24T15:16:00Z",
        },
        {
          commentId: "45678-876-54321",
          username: "emilyturner",
          picUrl: "http://bit.ly/42Zm7tM",
          likes: 1,
          comment: "I've been wanting to learn Python. This is perfect timing!",
          createdAt: "2023-06-24T15:17:00Z",
        },
      ],
      isBookmarked: false,
    },
  ],
};
